---
version: '2'
services:
  control-center:
    image: ${REPOSITORY}/cp-enterprise-control-center:${CONFLUENT_DOCKER_TAG}
    hostname: control-center
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS

      CONTROL_CENTER_SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
      CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE: $BASIC_AUTH_CREDENTIALS_SOURCE
      CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: $SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO

      CONTROL_CENTER_CONNECT_LOCAL_CLUSTER: http://connect-local:8083
      CONTROL_CENTER_CONNECT_CLOUD_CLUSTER: http://connect-cloud:8087

      CONTROL_CENTER_KAFKA_LOCAL_BOOTSTRAP_SERVERS: kafka:29092
      CONTROL_CENTER_KAFKA_CLOUD_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
      CONTROL_CENTER_KAFKA_CLOUD_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_KAFKA_CLOUD_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      CONTROL_CENTER_KAFKA_CLOUD_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_KAFKA_CLOUD_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"

      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_REPLICATION_FACTOR: 2
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 3
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 3
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 3
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 3
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 3
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 4
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 4

      # Workaround for MMA-3564
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
      CONFLUENT_METRICS_TOPIC_REPLICATION: 3
      PORT: 9021
